# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=254, unique=True)),
                ('smobile', models.IntegerField(unique=True)),
                ('spassword', models.CharField(max_length=20)),
                ('sclg', models.CharField(max_length=50)),
            ],
        ),
    ]
