# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180728_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Events'),
        ),
        migrations.AlterField(
            model_name='events',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Department'),
        ),
    ]
