# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-28 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180728_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dimage',
            field=models.ImageField(blank=True, upload_to='images/departments'),
        ),
    ]
