# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-30 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180730_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='cmobile',
            field=models.CharField(max_length=13),
        ),
    ]
